"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_Clients_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_Procedures_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_DataVitals_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_DataMeds_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_DataDiagnoses_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_DataImmuns_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_Sessions_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_Scheds_00.sql
"C:\Program Files\MySQL\MySQL Server 5.1\bin\mysql.exe" -uroot -pclick01 -Demrtest < SQL_G0001_TrackItems_00.sql